"""Seed data for the first Python Backend Developer learning path."""

GOALS = [{'id': 'goal_python_backend',
  'title': 'Python Backend Developer',
  'description': 'Build a small FastAPI backend and understand the learning loop.'}]

TOPICS = [{'id': 'topic_python_variables',
  'goal_id': 'goal_python_backend',
  'title': 'Python variables',
  'skill_id': 'skill_python_variables',
  'order': 1},
 {'id': 'topic_http_api_basics',
  'goal_id': 'goal_python_backend',
  'title': 'HTTP and API basics',
  'skill_id': 'skill_http_api_basics',
  'order': 2},
 {'id': 'topic_fastapi_routes',
  'goal_id': 'goal_python_backend',
  'title': 'FastAPI routes',
  'skill_id': 'skill_fastapi_routes',
  'order': 3},
 {'id': 'topic_database_basics',
  'goal_id': 'goal_python_backend',
  'title': 'Database basics',
  'skill_id': 'skill_database_basics',
  'order': 4}]

EXERCISES = [{'id': 'ex_python_variables_1',
  'topic_id': 'topic_python_variables',
  'skill_id': 'skill_python_variables',
  'title': 'Create your first variable',
  'prompt': 'Create a variable named x with the value 5.',
  'expected_answer': 'x = 5',
  'acceptable_answers': ['x=5', 'x = 5'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Use the assignment operator = between the variable name and the value.',
  'solution': 'x = 5',
  'explanation': 'A variable stores a value under a name. Here, x becomes a name for the number 5.',
  'incorrect_feedback': 'Check the variable name and use = for assignment.',
  'order': 1},
 {'id': 'ex_python_variables_2',
  'topic_id': 'topic_python_variables',
  'skill_id': 'skill_python_variables',
  'title': 'Update a variable value',
  'prompt': 'Create a variable named score with the value 10, then update it to 15.',
  'expected_answer': 'score = 10\nscore = 15',
  'acceptable_answers': ['score=10\nscore=15', 'score = 10\nscore = 15'],
  'difficulty': 'medium',
  'estimated_minutes': 3,
  'hint': 'Write two assignments. The second assignment replaces the first value.',
  'solution': 'score = 10\nscore = 15',
  'explanation': 'Python variables can be reassigned. After the second line, score stores 15.',
  'incorrect_feedback': 'Make sure the variable is named score and the final value is 15.',
  'order': 2},
 {'id': 'ex_http_api_basics_1',
  'topic_id': 'topic_http_api_basics',
  'skill_id': 'skill_http_api_basics',
  'title': 'Choose the read method',
  'prompt': 'Which HTTP method should an API usually use to read data without changing it?',
  'expected_answer': 'GET',
  'acceptable_answers': ['GET', 'get'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Think about the method browsers use when opening a page URL.',
  'solution': 'GET',
  'explanation': 'GET is normally used for safe read operations, like listing goals or exercises.',
  'incorrect_feedback': 'For reading data, use GET. POST is usually for creating or submitting '
                        'data.',
  'order': 3},
 {'id': 'ex_fastapi_health_1',
  'topic_id': 'topic_fastapi_routes',
  'skill_id': 'skill_fastapi_routes',
  'title': 'Health endpoint response',
  'prompt': 'What JSON should the health endpoint return when the backend is OK?',
  'expected_answer': '{"status": "ok"}',
  'acceptable_answers': ['{"status":"ok"}', '{"status": "ok"}'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Return one JSON object with a status key and ok as the value.',
  'solution': '{"status": "ok"}',
  'explanation': 'A health endpoint gives clients and deployment platforms a simple way to check '
                 'that the API is alive.',
  'incorrect_feedback': 'The response should be a JSON object with status equal to ok.',
  'order': 4},
 {'id': 'ex_fastapi_routes_2',
  'topic_id': 'topic_fastapi_routes',
  'skill_id': 'skill_fastapi_routes',
  'title': 'Create a route decorator',
  'prompt': 'Write the FastAPI decorator for a GET route at /api/v1/health using an app object '
            'named app.',
  'expected_answer': '@app.get("/api/v1/health")',
  'acceptable_answers': ["@app.get('/api/v1/health')", '@app.get("/api/v1/health")'],
  'difficulty': 'medium',
  'estimated_minutes': 4,
  'hint': 'FastAPI route decorators look like @app.get("/path").',
  'solution': '@app.get("/api/v1/health")',
  'explanation': 'The decorator tells FastAPI which URL and HTTP method should call the function '
                 'below it.',
  'incorrect_feedback': 'Use app.get and put the path /api/v1/health inside the parentheses.',
  'order': 5},
 {'id': 'ex_database_basics_1',
  'topic_id': 'topic_database_basics',
  'skill_id': 'skill_database_basics',
  'title': 'Select all users',
  'prompt': 'Write a SQL query that selects all columns from a table named users.',
  'expected_answer': 'SELECT * FROM users;',
  'acceptable_answers': ['SELECT * FROM users', 'SELECT * FROM users;', 'select * from users;'],
  'difficulty': 'easy',
  'estimated_minutes': 3,
  'hint': 'Use SELECT * when you want all columns from a table.',
  'solution': 'SELECT * FROM users;',
  'explanation': 'SELECT reads data. The * means all columns, and FROM users chooses the table.',
  'incorrect_feedback': 'Use SELECT, then *, then FROM users.',
  'order': 6}]

TOPICS.extend([
    {
        "id": "topic_python_functions",
        "goal_id": "goal_python_backend",
        "title": "Python functions",
        "skill_id": "skill_python_functions",
        "order": 5,
    },
    {
        "id": "topic_python_conditionals",
        "goal_id": "goal_python_backend",
        "title": "Python conditionals",
        "skill_id": "skill_python_conditionals",
        "order": 6,
    },
    {
        "id": "topic_python_lists",
        "goal_id": "goal_python_backend",
        "title": "Python lists",
        "skill_id": "skill_python_lists",
        "order": 7,
    },
    {
        "id": "topic_pydantic_models",
        "goal_id": "goal_python_backend",
        "title": "Pydantic models",
        "skill_id": "skill_pydantic_models",
        "order": 8,
    },
    {
        "id": "topic_fastapi_query_params",
        "goal_id": "goal_python_backend",
        "title": "FastAPI query parameters",
        "skill_id": "skill_fastapi_query_params",
        "order": 9,
    },
    {
        "id": "topic_fastapi_post_body",
        "goal_id": "goal_python_backend",
        "title": "FastAPI request body",
        "skill_id": "skill_fastapi_post_body",
        "order": 10,
    },
    {
        "id": "topic_sql_filters",
        "goal_id": "goal_python_backend",
        "title": "SQL filters",
        "skill_id": "skill_sql_filters",
        "order": 11,
    },
    {
        "id": "topic_api_errors",
        "goal_id": "goal_python_backend",
        "title": "API errors",
        "skill_id": "skill_api_errors",
        "order": 12,
    },
])

EXERCISES.extend([
    {
        "id": "ex_python_functions_1",
        "topic_id": "topic_python_functions",
        "skill_id": "skill_python_functions",
        "title": "Define a simple function",
        "prompt": "Write a Python function named add that accepts a and b, then returns their sum.",
        "expected_answer": "def add(a, b):\n    return a + b",
        "acceptable_answers": [
            "def add(a,b):\n    return a+b",
            "def add(a, b):\n    return a + b",
        ],
        "difficulty": "easy",
        "estimated_minutes": 4,
        "hint": "Use def, put the parameters in parentheses, and return a + b.",
        "solution": "def add(a, b):\n    return a + b",
        "explanation": "Functions package reusable behavior. This function receives two values and returns their sum.",
        "incorrect_feedback": "Check the function name, parameters, and return statement.",
        "order": 7,
    },
    {
        "id": "ex_python_functions_2",
        "topic_id": "topic_python_functions",
        "skill_id": "skill_python_functions",
        "title": "Call a function",
        "prompt": "Call the add function with 2 and 3, and store the result in a variable named total.",
        "expected_answer": "total = add(2, 3)",
        "acceptable_answers": ["total=add(2,3)", "total = add(2, 3)"],
        "difficulty": "easy",
        "estimated_minutes": 3,
        "hint": "Put the function call on the right side of an assignment.",
        "solution": "total = add(2, 3)",
        "explanation": "Calling a function runs it. The returned value can be stored in a variable.",
        "incorrect_feedback": "Use total as the variable name and call add with 2 and 3.",
        "order": 8,
    },
    {
        "id": "ex_python_conditionals_1",
        "topic_id": "topic_python_conditionals",
        "skill_id": "skill_python_conditionals",
        "title": "Check a status code",
        "prompt": "Write an if statement that checks whether status_code equals 200.",
        "expected_answer": "if status_code == 200:",
        "acceptable_answers": ["if status_code==200:", "if status_code == 200:"],
        "difficulty": "easy",
        "estimated_minutes": 3,
        "hint": "Use == for comparison and end the line with a colon.",
        "solution": "if status_code == 200:",
        "explanation": "Conditionals let code branch based on a boolean expression.",
        "incorrect_feedback": "Use == instead of =, and remember the colon.",
        "order": 9,
    },
    {
        "id": "ex_python_conditionals_2",
        "topic_id": "topic_python_conditionals",
        "skill_id": "skill_python_conditionals",
        "title": "Return an auth result",
        "prompt": "Write one line that returns True when is_authenticated is true, otherwise returns False.",
        "expected_answer": "return True if is_authenticated else False",
        "acceptable_answers": [
            "return True if is_authenticated else False",
            "return bool(is_authenticated)",
        ],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "You can use a conditional expression or convert the value to bool.",
        "solution": "return True if is_authenticated else False",
        "explanation": "A conditional expression chooses one value when the condition is true and another when it is false.",
        "incorrect_feedback": "Return a boolean value based on is_authenticated.",
        "order": 10,
    },
    {
        "id": "ex_python_lists_1",
        "topic_id": "topic_python_lists",
        "skill_id": "skill_python_lists",
        "title": "Create a list of topics",
        "prompt": "Create a list named topics with two strings: 'python' and 'fastapi'.",
        "expected_answer": "topics = ['python', 'fastapi']",
        "acceptable_answers": [
            "topics=['python','fastapi']",
            "topics = ['python', 'fastapi']",
            'topics = ["python", "fastapi"]',
        ],
        "difficulty": "easy",
        "estimated_minutes": 3,
        "hint": "Use square brackets and separate values with a comma.",
        "solution": "topics = ['python', 'fastapi']",
        "explanation": "Lists store ordered collections. Here the list contains two topic names.",
        "incorrect_feedback": "Use the variable name topics and include both strings in a list.",
        "order": 11,
    },
    {
        "id": "ex_python_lists_2",
        "topic_id": "topic_python_lists",
        "skill_id": "skill_python_lists",
        "title": "Append a topic",
        "prompt": "Append the string 'sql' to the topics list.",
        "expected_answer": "topics.append('sql')",
        "acceptable_answers": ["topics.append('sql')", 'topics.append("sql")'],
        "difficulty": "easy",
        "estimated_minutes": 2,
        "hint": "Use the list append method.",
        "solution": "topics.append('sql')",
        "explanation": "append adds one new item to the end of a list.",
        "incorrect_feedback": "Call append on the topics list with the value sql.",
        "order": 12,
    },
    {
        "id": "ex_pydantic_models_1",
        "topic_id": "topic_pydantic_models",
        "skill_id": "skill_pydantic_models",
        "title": "Import BaseModel",
        "prompt": "Write the import line for BaseModel from pydantic.",
        "expected_answer": "from pydantic import BaseModel",
        "acceptable_answers": ["from pydantic import BaseModel"],
        "difficulty": "easy",
        "estimated_minutes": 2,
        "hint": "Use from ... import ... syntax.",
        "solution": "from pydantic import BaseModel",
        "explanation": "FastAPI commonly uses Pydantic models to validate request and response data.",
        "incorrect_feedback": "Import BaseModel from pydantic exactly.",
        "order": 13,
    },
    {
        "id": "ex_pydantic_models_2",
        "topic_id": "topic_pydantic_models",
        "skill_id": "skill_pydantic_models",
        "title": "Create a request schema",
        "prompt": "Write the class header for a Pydantic model named CreateUserRequest that inherits from BaseModel.",
        "expected_answer": "class CreateUserRequest(BaseModel):",
        "acceptable_answers": ["class CreateUserRequest(BaseModel):"],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "Use class Name(BaseModel):",
        "solution": "class CreateUserRequest(BaseModel):",
        "explanation": "A Pydantic model is a class. Inheriting from BaseModel gives validation behavior.",
        "incorrect_feedback": "Check the class name and inherit from BaseModel.",
        "order": 14,
    },
    {
        "id": "ex_fastapi_query_params_1",
        "topic_id": "topic_fastapi_query_params",
        "skill_id": "skill_fastapi_query_params",
        "title": "Add an optional query parameter",
        "prompt": "Write a function parameter named skill_id that can be str or None and defaults to None.",
        "expected_answer": "skill_id: str | None = None",
        "acceptable_answers": ["skill_id: str | None = None", "skill_id:str|None=None"],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "Use a union type and a default value.",
        "solution": "skill_id: str | None = None",
        "explanation": "FastAPI treats simple function parameters as query parameters when they are not part of the path or body.",
        "incorrect_feedback": "Use skill_id, allow str or None, and default it to None.",
        "order": 15,
    },
    {
        "id": "ex_fastapi_query_params_2",
        "topic_id": "topic_fastapi_query_params",
        "skill_id": "skill_fastapi_query_params",
        "title": "Filter by difficulty",
        "prompt": "Write a Python condition that is true when difficulty is None or exercise['difficulty'] equals difficulty.",
        "expected_answer": "difficulty is None or exercise['difficulty'] == difficulty",
        "acceptable_answers": [
            "difficulty is None or exercise['difficulty'] == difficulty",
            'difficulty is None or exercise["difficulty"] == difficulty',
        ],
        "difficulty": "medium",
        "estimated_minutes": 5,
        "hint": "Combine two checks with or.",
        "solution": "difficulty is None or exercise['difficulty'] == difficulty",
        "explanation": "Optional filters usually pass everything when the filter value is None.",
        "incorrect_feedback": "Allow None first, then compare the exercise difficulty.",
        "order": 16,
    },
    {
        "id": "ex_fastapi_post_body_1",
        "topic_id": "topic_fastapi_post_body",
        "skill_id": "skill_fastapi_post_body",
        "title": "POST route decorator",
        "prompt": "Write the FastAPI decorator for a POST route at /api/v1/attempts using an app object named app.",
        "expected_answer": "@app.post('/api/v1/attempts')",
        "acceptable_answers": ["@app.post('/api/v1/attempts')", '@app.post("/api/v1/attempts")'],
        "difficulty": "easy",
        "estimated_minutes": 3,
        "hint": "Use app.post with the path inside parentheses.",
        "solution": "@app.post('/api/v1/attempts')",
        "explanation": "POST routes are commonly used for actions that submit data, like attempts.",
        "incorrect_feedback": "Use @app.post and the /api/v1/attempts path.",
        "order": 17,
    },
    {
        "id": "ex_fastapi_post_body_2",
        "topic_id": "topic_fastapi_post_body",
        "skill_id": "skill_fastapi_post_body",
        "title": "Declare a request body parameter",
        "prompt": "Write a function parameter named payload with type SubmitAttemptRequest.",
        "expected_answer": "payload: SubmitAttemptRequest",
        "acceptable_answers": ["payload: SubmitAttemptRequest", "payload:SubmitAttemptRequest"],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "Use parameter_name: TypeName.",
        "solution": "payload: SubmitAttemptRequest",
        "explanation": "FastAPI uses Pydantic model parameters as request bodies.",
        "incorrect_feedback": "Use payload as the parameter name and SubmitAttemptRequest as its type.",
        "order": 18,
    },
    {
        "id": "ex_sql_filters_1",
        "topic_id": "topic_sql_filters",
        "skill_id": "skill_sql_filters",
        "title": "Select a user by email",
        "prompt": "Write a SQL query that selects all columns from users where email equals 'test@example.com'.",
        "expected_answer": "SELECT * FROM users WHERE email = 'test@example.com';",
        "acceptable_answers": [
            "SELECT * FROM users WHERE email = 'test@example.com';",
            "SELECT * FROM users WHERE email='test@example.com';",
            "select * from users where email = 'test@example.com';",
        ],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "Use WHERE to filter rows.",
        "solution": "SELECT * FROM users WHERE email = 'test@example.com';",
        "explanation": "WHERE filters rows so the database returns only matching records.",
        "incorrect_feedback": "Use SELECT * FROM users and a WHERE email condition.",
        "order": 19,
    },
    {
        "id": "ex_sql_filters_2",
        "topic_id": "topic_sql_filters",
        "skill_id": "skill_sql_filters",
        "title": "Order topics",
        "prompt": "Write a SQL query that selects all rows from topics ordered by the order column ascending.",
        "expected_answer": "SELECT * FROM topics ORDER BY order ASC;",
        "acceptable_answers": [
            "SELECT * FROM topics ORDER BY order ASC;",
            "SELECT * FROM topics ORDER BY order;",
            "select * from topics order by order asc;",
        ],
        "difficulty": "medium",
        "estimated_minutes": 4,
        "hint": "Use ORDER BY after the table name.",
        "solution": "SELECT * FROM topics ORDER BY order ASC;",
        "explanation": "ORDER BY controls result ordering. ASC means ascending order.",
        "incorrect_feedback": "Select from topics and order by the order column.",
        "order": 20,
    },
    {
        "id": "ex_api_errors_1",
        "topic_id": "topic_api_errors",
        "skill_id": "skill_api_errors",
        "title": "Raise a 404 error",
        "prompt": "Write one line that raises HTTPException with status_code=404 and detail='Exercise not found.'.",
        "expected_answer": "raise HTTPException(status_code=404, detail='Exercise not found.')",
        "acceptable_answers": [
            "raise HTTPException(status_code=404, detail='Exercise not found.')",
            'raise HTTPException(status_code=404, detail="Exercise not found.")',
        ],
        "difficulty": "medium",
        "estimated_minutes": 5,
        "hint": "Use raise HTTPException(...).",
        "solution": "raise HTTPException(status_code=404, detail='Exercise not found.')",
        "explanation": "APIs should return clear HTTP errors when requested resources do not exist.",
        "incorrect_feedback": "Use HTTPException with status_code 404 and the exact detail message.",
        "order": 21,
    },
    {
        "id": "ex_api_errors_2",
        "topic_id": "topic_api_errors",
        "skill_id": "skill_api_errors",
        "title": "Choose the unauthorized status code",
        "prompt": "Which HTTP status code should an API usually return when authentication is required but missing?",
        "expected_answer": "401",
        "acceptable_answers": ["401", "HTTP 401", "401 Unauthorized"],
        "difficulty": "easy",
        "estimated_minutes": 2,
        "hint": "Think about unauthenticated access, not missing resources.",
        "solution": "401",
        "explanation": "401 Unauthorized means the client must authenticate before accessing the resource.",
        "incorrect_feedback": "Use 401 for missing or invalid authentication.",
        "order": 22,
    },
])
