"""Seed data for the first Python Backend Developer learning path."""

GOALS = [{'id': 'goal_python_backend',
  'title': 'Python Backend Developer',
  'description': 'Build a small FastAPI backend and understand the learning loop.'}]

TOPICS = [{'id': 'topic_python_variables',
  'goal_id': 'goal_python_backend',
  'title': 'Python variables',
  'skill_id': 'skill_python_variables',
  'order': 1},
 {'id': 'topic_http_api_basics',
  'goal_id': 'goal_python_backend',
  'title': 'HTTP and API basics',
  'skill_id': 'skill_http_api_basics',
  'order': 2},
 {'id': 'topic_fastapi_routes',
  'goal_id': 'goal_python_backend',
  'title': 'FastAPI routes',
  'skill_id': 'skill_fastapi_routes',
  'order': 3},
 {'id': 'topic_database_basics',
  'goal_id': 'goal_python_backend',
  'title': 'Database basics',
  'skill_id': 'skill_database_basics',
  'order': 4}]

EXERCISES = [{'id': 'ex_python_variables_1',
  'topic_id': 'topic_python_variables',
  'skill_id': 'skill_python_variables',
  'title': 'Create your first variable',
  'prompt': 'Create a variable named x with the value 5.',
  'expected_answer': 'x = 5',
  'acceptable_answers': ['x=5', 'x = 5'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Use the assignment operator = between the variable name and the value.',
  'solution': 'x = 5',
  'explanation': 'A variable stores a value under a name. Here, x becomes a name for the number 5.',
  'incorrect_feedback': 'Check the variable name and use = for assignment.',
  'order': 1},
 {'id': 'ex_python_variables_2',
  'topic_id': 'topic_python_variables',
  'skill_id': 'skill_python_variables',
  'title': 'Update a variable value',
  'prompt': 'Create a variable named score with the value 10, then update it to 15.',
  'expected_answer': 'score = 10\nscore = 15',
  'acceptable_answers': ['score=10\nscore=15', 'score = 10\nscore = 15'],
  'difficulty': 'medium',
  'estimated_minutes': 3,
  'hint': 'Write two assignments. The second assignment replaces the first value.',
  'solution': 'score = 10\nscore = 15',
  'explanation': 'Python variables can be reassigned. After the second line, score stores 15.',
  'incorrect_feedback': 'Make sure the variable is named score and the final value is 15.',
  'order': 2},
 {'id': 'ex_http_api_basics_1',
  'topic_id': 'topic_http_api_basics',
  'skill_id': 'skill_http_api_basics',
  'title': 'Choose the read method',
  'prompt': 'Which HTTP method should an API usually use to read data without changing it?',
  'expected_answer': 'GET',
  'acceptable_answers': ['GET', 'get'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Think about the method browsers use when opening a page URL.',
  'solution': 'GET',
  'explanation': 'GET is normally used for safe read operations, like listing goals or exercises.',
  'incorrect_feedback': 'For reading data, use GET. POST is usually for creating or submitting '
                        'data.',
  'order': 3},
 {'id': 'ex_fastapi_health_1',
  'topic_id': 'topic_fastapi_routes',
  'skill_id': 'skill_fastapi_routes',
  'title': 'Health endpoint response',
  'prompt': 'What JSON should the health endpoint return when the backend is OK?',
  'expected_answer': '{"status": "ok"}',
  'acceptable_answers': ['{"status":"ok"}', '{"status": "ok"}'],
  'difficulty': 'easy',
  'estimated_minutes': 2,
  'hint': 'Return one JSON object with a status key and ok as the value.',
  'solution': '{"status": "ok"}',
  'explanation': 'A health endpoint gives clients and deployment platforms a simple way to check '
                 'that the API is alive.',
  'incorrect_feedback': 'The response should be a JSON object with status equal to ok.',
  'order': 4},
 {'id': 'ex_fastapi_routes_2',
  'topic_id': 'topic_fastapi_routes',
  'skill_id': 'skill_fastapi_routes',
  'title': 'Create a route decorator',
  'prompt': 'Write the FastAPI decorator for a GET route at /api/v1/health using an app object '
            'named app.',
  'expected_answer': '@app.get("/api/v1/health")',
  'acceptable_answers': ["@app.get('/api/v1/health')", '@app.get("/api/v1/health")'],
  'difficulty': 'medium',
  'estimated_minutes': 4,
  'hint': 'FastAPI route decorators look like @app.get("/path").',
  'solution': '@app.get("/api/v1/health")',
  'explanation': 'The decorator tells FastAPI which URL and HTTP method should call the function '
                 'below it.',
  'incorrect_feedback': 'Use app.get and put the path /api/v1/health inside the parentheses.',
  'order': 5},
 {'id': 'ex_database_basics_1',
  'topic_id': 'topic_database_basics',
  'skill_id': 'skill_database_basics',
  'title': 'Select all users',
  'prompt': 'Write a SQL query that selects all columns from a table named users.',
  'expected_answer': 'SELECT * FROM users;',
  'acceptable_answers': ['SELECT * FROM users', 'SELECT * FROM users;', 'select * from users;'],
  'difficulty': 'easy',
  'estimated_minutes': 3,
  'hint': 'Use SELECT * when you want all columns from a table.',
  'solution': 'SELECT * FROM users;',
  'explanation': 'SELECT reads data. The * means all columns, and FROM users chooses the table.',
  'incorrect_feedback': 'Use SELECT, then *, then FROM users.',
  'order': 6}]
